language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t dzuongld/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dzuongld/docker-react npm run test -- --coverage
